# Generated by Django 5.0.1 on 2024-02-02 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('dateCreation', models.DateField()),
                ('dateEnd', models.DateField()),
                ('url', models.CharField(max_length=250)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.SmallIntegerField(default=0)),
                ('progression', models.CharField(choices=[('AC', "J'ai compris"), ('IP', 'Je dois encore pratiquer'), ('NA', "C'est flou")], default='NA', max_length=2)),
                ('difficulty', models.CharField(choices=[('EA', 'Facile'), ('NO', 'OK'), ('HA', 'Un peu compliqué'), ('VA', 'Très compliqué'), ('EX', 'Au secours')], default='EX', max_length=2)),
                ('dateSend', models.DateField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='python2_django.sessionsurvey')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
