# Generated by Django 5.0.1 on 2024-02-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python2_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionsurvey',
            name='dateCreation',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sessionsurvey',
            name='dateEnd',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='surveyanswer',
            name='dateSend',
            field=models.DateTimeField(),
        ),
    ]
