# Generated by Django 5.0.1 on 2024-02-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python2_django', '0002_alter_sessionsurvey_datecreation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionsurvey',
            old_name='dateCreation',
            new_name='dateStarted',
        ),
    ]
