# Generated by Django 5.0.1 on 2024-02-06 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python2_django', '0004_alter_sessionsurvey_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyanswer',
            name='dateInitialSend',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 19, 46, 45, 999645, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
